### ISSUE TITLE
ENH: Metric for the distance in MDM 

### ISSUE THREAD

**Issue by alexandrebarachant** [alexandrebarachant/pyRiemann#10]
We should be able to specify the metric for the distance in MDM.
The metric for the distance and the mean can be different.

The argument metric should be used like this : 
if it is a string, use the same metric for mean and distance.
otherwise, we can pass a dict like `metric = dict(mean = 'logeuclid', distance = 'riemann')`

**Comment by kingjr** [comment]
When would it be useful to have distinct metrics for the mean and the distance?

Otherwise +1 for the API.

**Comment by alexandrebarachant** [comment]
Generally speaking, the best metric for the distance is the Riemannian metric. In some case, the metric for the mean is less critical. so you can choose another metric in order to speed up the `fit` (for example the log euclidean metric), and achieve very similar performances.
