### ISSUE TITLE
Make pyRiemann citable

### ISSUE THREAD

**Issue by wmvanvliet** [alexandrebarachant/pyRiemann#12]
I'm actually using your implementation of XDawn in one of my studies. I would like to include a proper citation to the source (for now I mention the URL). Github supports generating proper DOI's though, which are easier to cite.

**Comment by alexandrebarachant** [comment]
Great, I will take care of this later today. 

My implementation of XDAWN is actually a bit simplified from the one in the original paper. I wanted to keep something similar to the sklearn API where you can feed the algorithm epoched signal. This implementation is equivalent to XDawn in the case you ERP are not overlapped in time. It is also a generalisation to the multiclass case.
I have a true implementation, but i did not commit it. The main difference is in the way you estimates the averaged responses before using them to build the spatial filters.

**Comment by wmvanvliet** [comment]
In my experiment, the ERPs are non-overlapping.

Apart from API issues, the original method's way of dealing with overlapping trials is very computationally/memory heavy.

**Comment by alexandrebarachant** [comment]
Yep, this is also the other reason why i made this implementation.
I should rename this FastXDawn, and propose a true implementation (MNE may be a better place actually)

**Comment by alexandrebarachant** [comment]
DOI created. See the readme.md for the identifier

**Comment by wmvanvliet** [comment]
Yay!

Small detail: the bibtex looks a bit weird:

    @misc{alexandre_barachant_2015_18982,
      author       = {alexandre barachant and
                      J-R King},
      title        = {pyRiemann 0.2.2},
      month        = jun,
      year         = 2015,
      doi          = {10.5281/zenodo.18982},
      url          = {http://dx.doi.org/10.5281/zenodo.18982}
    }

Your name is not capitalized and is J-R  supposed to be J. R. ?

**Comment by alexandrebarachant** [comment]
Ok, i will change that.
I did not pay too much attention during the process.
I don't know for J-R., he just made a small PR a few days ago. Looks like he usedJ-R. for his articles : https://sites.google.com/site/jeanremiking/publications

**Comment by alexandrebarachant** [comment]
Ok, change will probably be effective on the next release.
In the meantime, you can use this : 
```
@misc{alexandre_barachant_2015_18982,
  author       = {A. Barachant and
                  J-R. King},
  title        = {pyRiemann v0.2.2},
  month        = jun,
  year         = 2015,
  doi          = {10.5281/zenodo.18982},
  url          = {http://dx.doi.org/10.5281/zenodo.18982}
}
```

**Comment by wmvanvliet** [comment]
thanks!

**Comment by agramfort** [comment]
>
> Yep, this is also the other reason why i made this implementation.
> I should rename this FastXDawn, and propose a true implementation (MNE may
> be a better place actually)
>
+1 !

>
>

**Comment by kingjr** [comment]
Oh, don't put me in the authors, I haven't done a thing!
