### ISSUE TITLE
problem with ptest.print() 

### ISSUE THREAD

**Issue by JonathanTristramMiller** [alexandrebarachant/pyRiemann#15]
I've been using pyRiemann for several days and it's working very well - very impressive.  I did have an issue with the ptest.print() function - maybe I am not initializing something correctly.   Anyway, here's a demo:

![capture](https://cloud.githubusercontent.com/assets/11357729/9553830/ac53cf62-4d8f-11e5-947b-7281e174167d.JPG)

for me, it produces this output:

![capture2](https://cloud.githubusercontent.com/assets/11357729/9553881/fdbbe56a-4d8f-11e5-9180-847d45a452db.JPG)

Thanks Alex,
Jonathan Miller.

**Comment by alexandrebarachant** [comment]
Hi Jonahathan,
Thank you for your feedback.

I actually made a mistake in my example code, because i rename the print() method to summary() to mimic the standard API.

so, instead of `ptest.print()`, use `print(ptest.summary())`  

Again, sorry about that.
I'm closing the issue.

**Comment by JonathanTristramMiller** [comment]
Thanks Alex,
Works fine.
Jonathan.
