### ISSUE TITLE
Py3k

### ISSUE THREAD

**Issue by jona-sassenhagen** [alexandrebarachant/pyRiemann#17]
Are you planning on Python 3 support?

**Comment by alexandrebarachant** [comment]
It's planned, in the near future. I have to switch my python stack to 3.x to see the amount of work.
did you tried it ?

**Comment by jona-sassenhagen** [comment]
I don't have Python 2 setup right now ... I'm very excited about the idea of a transform where linear filters don't matter anymore.

**Comment by alexandrebarachant** [comment]
Most of the code rely on numpy, scipy and sklearn. You can install the package from source and try to run the test suite or an example.
I tried my best keeping things compatible, but i can not guaranty anything since it's not tested.

**Comment by jona-sassenhagen** [comment]
Close because it seems to work on Py3 right now!
