### ISSUE TITLE
ValueError: array must not contain infs or NaNs

### ISSUE THREAD

**Issue by Sarwat-Fatima** [alexandrebarachant/pyRiemann#26]
If I follow the 1st example mentioned in the description under "how to use it" I get the following error. The dataset has 578 trials, 306 channels, 375 time points. 

#Error: 
"array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

#Code: 

import pyriemann
from sklearn.cross_validation import cross_val_score

load your data
X = ... # your EEG data, in format Ntrials x Nchannels X Nsamples
y = ... # the labels

estimate covariances matrices
cov = pyriemann.estimation.Covariances().fit_transform(X)

 cross validation
mdm = pyriemann.classification.MDM()

accuracy = cross_val_score(mdm,cov,y)

print(accuracy.mean())

**Comment by kingjr** [comment]
Try using a `oas` solver for the covariance.

**Comment by Sarwat-Fatima** [comment]
Can you elaborate your answer? What do you mean by oas solver?

**Comment by kingjr** [comment]
Your dimensionality may be too large to obtain a positive definite covariance matrix which is required in the Riemann geometry, so you need to regularize.

You can change the estimator (not 'solver', my bad) when initializing: cov = `Covariance('oas')`

See also https://github.com/alexandrebarachant/pyRiemann/issues/14.

**Comment by Sarwat-Fatima** [comment]
Oh. I get it now. Thankyou. It's working.

**Comment by alexandrebarachant** [comment]
Yes, this error is due to matrices not being definite positive.

High dimensionality can give sub optimal results, depending on your SNR. if you data are evoked potential, try using `XdawnCovariances` which perform a dimensionality reduction. 

see this example : http://pythonhosted.org/pyriemann/auto_examples/ERP/plot_classify_EEG_tangentspace.html

**Comment by Sarwat-Fatima** [comment]
Okay. Thankyou. Also, while using the Matlab package for covariance toolbox for the same dataset, I get a warning "Warning : Nombre d'itï¿½rations maximum atteint". I think it is while calculation of Riemannian Mean. Can you tell me what does this warning mean and how can it affect the calculation of covariances or its mean & distances?
I also left a similar question at the toolbox on GitHub but I am not sure if you saw it. I hope you will answer it soon.

**Comment by alexandrebarachant** [comment]
indeed, i missed it. I answered the question in the other thread. This problem is not present in the python toolbox.
