### ISSUE TITLE
Python Compatibility Issues 

### ISSUE THREAD

**Issue by Sarwat-Fatima** [alexandrebarachant/pyRiemann#28]
I am trying to run the following code on Python 3.4, Spyder 2.3.8, Anaconda 4.0 but it gave me an issue 
AttributeError: 'range' object has no attribute 'pop' . 

So I moved to Python 2.7.12, Spyder 2.3.9, Anaconda 4.0 but the kernel keeps dying without any execution. 

data = loadmat(filename,squeeze_me=True);
XX = data['X'] trials x channels x time samples 
YY = data['y']
cov = pyriemann.estimation.Covariances(estimator = 'oas').fit_transform(XX)
cov = pyriemann.channelselection.ElectrodeSelection().fit(cov,YY)

How can  I run the toolbox for Python 3.4?

**Comment by alexandrebarachant** [comment]
Hi, 
Code is not tested for python 3.4, but it should run with minor modification

Can you put the full error trace ? looks like i'm using a function that has been deprecated but unless you gave me the line where it happens i can't fix it.

**Comment by Sarwat-Fatima** [comment]
Yes, sure! Here is the full error trace. 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Sarwat\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 685, in runfile
    execfile(filename, namespace)
  File "C:\Users\Sarwat\Anaconda3\lib\site-packages\spyderlib\widgets\externalshell\sitecustomize.py", line 85, in execfile
    exec(compile(open(filename, 'rb').read(), filename, 'exec'), namespace)
  File "C:/Users/Sarwat/Desktop/xdawnCovarianceMatrices.py", line 29, in <module>
    cov = pyriemann.channelselection.ElectrodeSelection().fit(cov,YY)
  File "C:\Users\Sarwat\Anaconda3\lib\site-packages\pyriemann\channelselection.py", line 93, in fit
    sub.pop(idx)
AttributeError: 'range' object has no attribute 'pop'

**Comment by alexandrebarachant** [comment]
Can you check the compatibility. If it still crash, re-open the issue with the Error trace.

**Comment by Sarwat-Fatima** [comment]
It's working now. Thankyou.
