### ISSUE TITLE
cannot run MDM example

### ISSUE THREAD

**Issue by nbara** [alexandrebarachant/pyRiemann#40]
Hi Alexandre,

I was trying the cross-validation classification example code from the [homepage](https://github.com/alexandrebarachant/pyRiemann#how-to-use-it) on some toy EEG data (64 channels), but I keep running into the following error:

![screen shot 2016-08-23 at 15 33 31](https://cloud.githubusercontent.com/assets/10333715/17893715/fbabde64-6946-11e6-9b94-3c62ef82312c.png)

I tracked the error down to the `mean_riemann` method . `logm(tmp)` ([line 61](https://github.com/alexandrebarachant/pyRiemann/blob/master/pyriemann/utils/mean.py#L61)) is filled with NaNs.

My input data is in the following format (Ntrials, Nchannels, Nsamples) : 

![screen shot 2016-08-23 at 15 38 48](https://cloud.githubusercontent.com/assets/10333715/17893906/b854e2d6-6947-11e6-849e-4ba82e29669e.png)

Let me know if you need more information.

Thanks!

**Comment by alexandrebarachant** [comment]
This is a common error when the data are rank deficient (high dimension or when a common average reference has been applied).
you have to regularize the covariance matrices by using `Covariances(estimator='lwf')`

I will make a FAQ for this one.

**Comment by nbara** [comment]
Aah, I should have thought of that ! Indeed I've removed eyeblinks w/ ICA !

Thanks for the prompt response :)

**Comment by kingjr** [comment]
Note that decoding is generally resistant to eye artefacts, so it might
actually not be a great idea to do an ICA-based clean up.

**Comment by nbara** [comment]
Noted, thanks!

**Comment by kingjr** [comment]
Alex, I think an explicit test/ error could help, wdyt?

**Comment by alexandrebarachant** [comment]
yep, i was thinking about the same thing.
we could catch the error and trow something more explicit.

i'm not found of testing for positivness, as the check in itself will slow everything down.

**Comment by kingjr** [comment]
Right, catching the nan should suffice. Is there any other reasons to get
nan than non positiveness?

Le 23 août 2016 16:33, "alexandre barachant" <notifications@github.com> a
écrit :

**Comment by alexandrebarachant** [comment]
To the best of my knowledge, this error is always fixed by regularization so it's safe to catch the ValueError and replace the error message.

@nbara what do you think of :

`ValueError: Covariance matrices must be positive definite. Add covariance regularization to avoid this error`

Would it be helpful ?
@kingjr other suggestion

**Comment by kingjr** [comment]
LGTM, perhaps add a isnan check before fitting to ensure this is indeed the
source  of the error (if not already done ?)

Le 23 août 2016 16:44, "alexandre barachant" <notifications@github.com> a
écrit :

**Comment by alexandrebarachant** [comment]
The nan is in the scipy function, so it's hard to catch. I will open a PR today.

**Comment by alexandrebarachant** [comment]
hum, i can also remove the `check_finite` in the [scipy](http://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.eigh.html) function and add my own test. let see.

**Comment by kingjr** [comment]
I mean check that X doesn't contain any nan in the first place, I suppose
it would throw a similar error, although that d need to be checked (sorry I
m in transit)

Le 23 août 2016 16:49, "alexandre barachant" <notifications@github.com> a
écrit :

**Comment by alexandrebarachant** [comment]
This check has to be done at the lowest level possible i.e. in the function `_matrix_operator` in `utils.base`. This function is called a huge amount of times so i would like to avoid making unnecessary check that will slow down the whole toolbox.
