### ISSUE TITLE
Cannot use anaconda to install

### ISSUE THREAD

**Issue by aj-ptw** [alexandrebarachant/pyRiemann#42]
Trying to set up a virtual environment to develop in across computers and when trying to use 

```
$ conda install -n MyVenv pyriemann 
```

I get:

```
Fetching package metadata .......
Solving package specifications: .
PackageNotFoundError: Package not found: '' Package missing in current osx-64 channels: 
  - pyriemann

You can search for packages on anaconda.org with

    anaconda search -t conda pyriemann
```

This also occurs when trying to simply do

```
conda install pyriemann
```

**Comment by iraquitan** [comment]
In the README it describes how to install the package:
```
$ pip install pyriemann
```
Anaconda is not currently supported, if you want to use anaconda, you need to create a virtual environment in anaconda, activate it and use the above command to install it.

**Comment by aj-ptw** [comment]
This should be closed good call thanks

**Comment by aj-ptw** [comment]
@iraquitan i copied and pasted your line into #48 thanks
