### ISSUE TITLE
Set threshold of Potato in real time

### ISSUE THREAD

**Issue by aj-ptw** [alexandrebarachant/pyRiemann#43]
Would be very nice if a user could change their threshold values because this seems to be both device dependent and and environment dependent. I picture having a little slider or something or dynamically working with the user to tune a proper value.

**Comment by alexandrebarachant** [comment]
the threshold is a normalized value (z-score). the default threshold of 3 represents 3 standard deviations from the mean and should be considered as a good value for most case (you can decrease it to 2.5 if you think it's not sensitive enough)

if you want to change the threshold in real time, just change the value of `self.threshold`

**Comment by aj-ptw** [comment]
Ok cool
