### ISSUE TITLE
Can't have class label other than 1 in Potato

### ISSUE THREAD

**Issue by aj-ptw** [alexandrebarachant/pyRiemann#44]
In reference to this line: https://github.com/alexandrebarachant/pyRiemann/blob/master/pyriemann/clustering.py#L316

I have been using `7` as my artifact class label and the potato crashes.

The docs say `y` is not used so I expected to be able to pass a `y` in and just have it be ignored.

**Comment by alexandrebarachant** [comment]
This is not a bug, it is how it is supposed to work.
the potato will return `1` for clean data and `0` for atrifact.

However, i added 2 arguments (`pos_label` and `neg_label`) in the constructor so you can specify them
