### ISSUE TITLE
Float numbers 

### ISSUE THREAD

**Issue by alexZ82** [alexandrebarachant/pyRiemann#57]
I used to get deprecation errors because a lot of pyriemmann return floats. 
Updating my packages results in
TypeError: 'float' object cannot be interpreted as an integer
Was the package developed in python 2? Should I replace all division with // ?

some places are
pyriemann/utils/tangentspace.py:20: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  T = numpy.empty((Nt, Ne * (Ne + 1) / 2))

pyriemann/utils/ajd.py", line 159, in ajd_pham
    tmp2 = (tmp*g12 - g21)/np.max(omega - 1, 1e-9)

**Comment by alexandrebarachant** [comment]
are you using python 3 ? 
if so, install pyriemann from the sources, it's compatible with python 3.
the pip version is way behind the sources and i plan top release a new one as soon as i find time to do it.

**Comment by alexZ82** [comment]
Thank you!
Yes that resolved it. 
Cheers
Alexia
