### ISSUE TITLE
1/N should be removed in formula. Code is without it. 

### ISSUE THREAD

**Issue by Schraivogel** [alexandrebarachant/pyRiemann#61]
http://pythonhosted.org/pyriemann/generated/pyriemann.utils.mean.mean_logeuclid.html#pyriemann.utils.mean.mean_logeuclid

Thanks for your work and sharing it

**Comment by alexandrebarachant** [comment]
it is, because the `sample_weight` is set to 1/N by default.

**Comment by Schraivogel** [comment]
ups, okay;)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-10-11 10:46 GMT+02:00 alexandre barachant <notifications@github.com>:
