### ISSUE TITLE
Q: regularize cospcovariances

### ISSUE THREAD

**Issue by kingjr** [alexandrebarachant/pyRiemann#62]
Hey Alex!

Is there a way to easily regularize `CospCovariances'?

I'm trying to do 
```python
clf = make_pipeline(
    CospCovariances(fmin=4., fmax=45, fs=500.),
    SlidingEstimator(
        make_pipeline(TangentSpace(), SVC(kernel='linear'))
)
```

but get the usual non positive definite error

Thanks!

**Comment by alexandrebarachant** [comment]
Not n the constructor, but you can place a Shrinkage (from
pyriemann.estimation) before your TangentSpace.

Le dim. 3 déc. 2017 21:28, Jean-Rémi KING <notifications@github.com> a
écrit :

**Comment by alexandrebarachant** [comment]
But a good way to avoid the error is to increase the overlapp in the
CospCovariance estimator.

**Comment by kingjr** [comment]
perfect thanks!
