### ISSUE TITLE
http://pythonhosted.org/pyriemann site not working properly.

### ISSUE THREAD

**Issue by abhiramsingh7** [alexandrebarachant/pyRiemann#63]
Webpage is not working properly. API reference page is showing 404 not found error on clicking on any function. example gallery is showing 404 not found. Please resolve the issue. Unable to use the package without going through the reference material.

**Comment by alexandrebarachant** [comment]
Thanks for reporting this. 
the documentation was previously hosted on pythonhosted, which service is not available anymore.
I'm trying to switch to readthedocs but i have issue on compiling the documentation on their service. This should be resolved soon.

**Comment by alexandrebarachant** [comment]
Hi, 

Doc is live at this adress : http://pyriemann.readthedocs.io/en/latest/index.html

I had to disable the gallery of example, so it's not complete, but at least you have the API doc

**Comment by alexandrebarachant** [comment]
some update on this one. I managed to have the gallery run with ReadTheDoc. The doc is back to normal
