### ISSUE TITLE
Cannot pip install with Python 3.6

### ISSUE THREAD

**Issue by septp** [alexandrebarachant/pyRiemann#68]
I tried to install pyRiemann in a Python 3.6 virtual environment by running:
`pip install pyriemann`
But the installation failed and the following error was printed:

> Could not find a version that satisfies the requirement pyreimman (from versions: )
No matching distribution found for pyreimman

I first thought that maybe the package is only Python 2 compatible. But I installed the package from source. The package imports with no errors. Also, I ran the tests in the Python 3 venv and all of them passed.

**Comment by cedricsimar** [comment]
According to your error message, you may have typed "pip install pyreimman" instead of "pip install pyriemann"

**Comment by septp** [comment]
Oops!
You're right, tnx :)
