### ISSUE TITLE
About Covariances

### ISSUE THREAD

**Issue by Lminto** [alexandrebarachant/pyRiemann#72]
thank you for this respository!
-----------------
X is my experiment data(trial * channel * sample)
```
cov = Covariances().fit_transform(X)
mdm = pyriemann.classification.MDM()
# cross validation
accuracy = cross_val_score(mdm, cov, y)
```

raise "ValueError:Covariance matrices must be positive definite. Add regularization to avoid this error"
so i try 
`cov = Covariances().fit_transform(X) + 0.001*np.eye(X.shape[1])`
it's OK
do you think the first ValueError is the result of calculation process?
what about adding some reminder about this?

**Comment by kingjr** [comment]
Hi,
This is a duplicate, see https://github.com/alexandrebarachant/pyRiemann/issues/65

hope that helps

**Comment by Lminto** [comment]
oh,sorry
thanks, i understand 'oas'
