### ISSUE TITLE
pyRiemann in MATLAB

### ISSUE THREAD

**Issue by awalece04ku** [alexandrebarachant/pyRiemann#73]
My General question is:
Do you have plan to implement pyRiemann in MATLAB? This could be very useful for Basic Matlab user like me. I know that there covariance toolbox but it is no longer maintained. 

Specific Question is: 
I am facing problem implementing CSP and SPoc for multiclass problem. Could you please provide multiclass implementation in matalb?
Thanks in advanced.

**Comment by alexandrebarachant** [comment]
The general question :

Nope, pyRiemann actually started when I moved from MATLAB to python, and was a re-implementation of my covariance toolbox. 

The specific question :

I'm fairly sure you can find a matlab implementation online somewhere. Saying that, if you are interested in EEG / Brain decoding, the python ecosystem is much more developed, so it could be the right time to give it a try.
