### ISSUE TITLE
Update to scikit-learn 0.22

### ISSUE THREAD

**Issue by sylvchev** [alexandrebarachant/pyRiemann#75]
Importing `pyriemann.clustering.Kmeans` raises a deprecation warning for scikit-learn

`FutureWarning: The sklearn.cluster.k_means_ module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.cluster. Anything that cannot be imported from sklearn.cluster is now part of the private API.`

I'll push an PR quickly

**Comment by alexandrebarachant** [comment]
Thanks for reporting this.

Yes, please make a PR :) Also, don't forget to update the `requirements.txt` with the correct version number.

**Comment by davestanley** [comment]
Likewise, there is an error `ModuleNotFoundError: No module named 'sklearn.cross_validation'` for the import in plot_classify_EEG_tangentspace:

`from sklearn.cross_validation import KFold`

Created a pull request to fix.

**Comment by alexandrebarachant** [comment]
Fixed
