### ISSUE TITLE
Online version of  Pyriemann for SSVEP

### ISSUE THREAD

**Issue by Carlongo** [alexandrebarachant/pyRiemann#88]
Hello Alexandre!

First of all, thanks for the great work!

I'm currently working on an implementation for SSVEP with Covariance + Tangent Space, but I can only find some online examples in Matlab. Do you know where I can find something in python?

Thanks!

**Comment by plcrodrigues** [comment]
Hi Carlos, 
I think this could be useful for you : https://github.com/NeuroTechX/moabb/blob/master/examples/plot_cross_subject_ssvep.py
Cheers,
Pedro

**Comment by Carlongo** [comment]
Thank you for your response @plcrodrigues !

Sorry for my late reply, it was a busy week :( 

I'll make my approach with this code now.

Best regards!
Carlos

**Comment by Carlongo** [comment]
Hello @plcrodrigues !

Just trying to understand something, I looked at this implementation but I can't see the part with the online training. Is there any other code with online training?

Thank you!

**Comment by plcrodrigues** [comment]
Hi, sorry, I should have been more explicit. No, there's no online implementation on the link I sent, but it is in python and deals with SSVEP... which is why I thought that could be useful for you :) hope it helps anyways
